/** Exercise the actual editor, tabs and pipeline controls in the static page. */
export async function runUiTests() {
  const checks = [];
  function assert(condition, name) { if (!condition) throw new Error(name); checks.push(name); }
  async function until(predicate, name, timeout = 120000) {
    const started = performance.now();
    while (!predicate()) {
      if (performance.now() - started > timeout) throw new Error(`Timed out waiting for ${name}`);
      await new Promise(resolve => setTimeout(resolve, 30));
    }
  }
  const el = id => document.getElementById(id);
  const click = id => el(id).click();
  await until(() => el('runtime-status')?.textContent === 'PYTHON READY' || el('runtime-status')?.textContent === 'PYTHON UNAVAILABLE', 'Python ready');
  if (el('runtime-status').textContent !== 'PYTHON READY') throw new Error(el('runtime-notice').textContent);
  const editor = document.querySelector('.CodeMirror')?.CodeMirror;
  assert(editor?.getValue() === 'print("Hello, world!")', 'existing CodeMirror editor remains editable');
  assert(document.querySelectorAll('[data-stage]').length === 7 && document.querySelectorAll('[data-tab]').length === 8, 'seven compact stages and eight result tabs are present');
  click('run-button');
  await until(() => el('runtime-status').textContent === 'PYTHON READY' && el('output-content').textContent.includes('Hello, world!'), 'default execution result', 20000);
  assert(el('output-content').textContent === 'Hello, world!\n', 'Run executes and shows stdout in the existing result panel');
  click('tab-tokens');
  assert(el('tab-tokens').getAttribute('aria-selected') === 'true' && !el('panel-tokens').hidden && el('tokens-body').children.length > 0, 'Tokens tab shows a structured table');
  document.querySelector('[data-stage="ast"]').click();
  assert(!el('panel-ast').hidden && el('ast-tree-content').textContent.startsWith('Module') && el('ast-dump-content').textContent.includes('Module('), 'AST stage opens both real representations');
  document.querySelector('[data-stage="code-object"]').click();
  assert(!el('panel-code-object').hidden && el('code-object-content').textContent.includes('co_filename: main.py'), 'Code object stage opens metadata');
  document.querySelector('[data-stage="bytecode"]').click();
  assert(!el('panel-bytecode').hidden && el('bytecode-content').textContent.includes('Offset'), 'Bytecode stage opens opcode table and raw bytes');
  document.querySelector('[data-stage="disassembly"]').click();
  assert(!el('panel-disassembly').hidden && el('disassembly-content').textContent.includes('LOAD_CONST'), 'Disassembly stage remains usable');
  document.querySelector('[data-stage="source"]').click();
  assert(editor.hasFocus(), 'Source stage returns keyboard focus to CodeMirror');
  editor.setValue('print(');
  click('run-button');
  await until(() => el('runtime-status').textContent === 'PYTHON READY' && el('errors-content').textContent.includes('SyntaxError'), 'syntax error result', 20000);
  click('tab-tokens');
  assert(el('tokens-warning').textContent.includes('SYNTAX ERROR') && el('tokens-body').children.length > 0, 'invalid source retains partial token table and warning');
  click('tab-ast');
  assert(el('ast-tree-content').textContent.startsWith('SYNTAX ERROR'), 'AST panel reports syntax error');
  click('tab-code-object');
  assert(el('code-object-content').textContent.includes('No code object'), 'code object panel explains invalid source');
  click('tab-bytecode');
  assert(el('bytecode-content').textContent.startsWith('SYNTAX ERROR'), 'bytecode panel clears previous run on syntax error');
  click('tab-disassembly');
  assert(el('disassembly-content').textContent.startsWith('SYNTAX ERROR'), 'disassembly panel remains available on syntax error');
  editor.setValue('print("<img src=x>")');
  document.querySelector('[data-stage="output"]').click();
  await until(() => el('runtime-status').textContent === 'PYTHON READY' && el('output-content').textContent.includes('<img src=x>'), 'pipeline Run result', 20000);
  assert(!el('panel-output').querySelector('img') && el('output-content').textContent === '<img src=x>\n', 'pipeline Run safely renders source output as text');

  editor.setValue('x = 10\ny = 20\nz = x + y\nprint(z)');
  click('run-button');
  await until(() => el('runtime-status').textContent === 'PYTHON READY' && el('output-content').textContent === '30\n', 'mapping execution', 20000);
  assert(el('bytecode-instructions').querySelectorAll('[data-instruction-id]').length > 0 && el('ast-node-list').querySelectorAll('[data-ast-id]').length > 0, 'real AST and bytecode rows are selectable');
  editor.setCursor({ line: 0, ch: 2 });
  assert(el('trace-content').textContent.includes('line 1') && el('trace-content').textContent.includes('10'), 'source line 1 reveals tokens and instructions');
  editor.setCursor({ line: 1, ch: 0 });
  assert(el('trace-content').textContent.includes('line 2') && el('trace-content').textContent.includes('20'), 'source line 2 has its own mapping');
  editor.setCursor({ line: 2, ch: 4 });
  assert(el('tab-trace').getAttribute('aria-selected') === 'true' && el('trace-content').textContent.includes('BinOp') && el('trace-content').textContent.includes('BINARY_OP'), 'source line 3 traces AST and bytecode');
  assert(el('ast-node-list').querySelector('.is-selected')?.textContent.includes('Name'), 'source region selects the smallest AST node');
  editor.setCursor({ line: 3, ch: 1 });
  assert(el('trace-content').textContent.includes('line 4') && el('trace-content').textContent.includes('CALL'), 'source line 4 has distinct execution instructions');
  click('tab-ast');
  [...el('ast-node-list').querySelectorAll('[data-ast-id]')].find(row => row.textContent.startsWith('BinOp')).click();
  assert(editor.getSelection() === 'x + y' && !!document.querySelector('.editor-trace-range') && el('ast-selected-detail').textContent.includes('BinOp'), 'AST selection highlights its exact CodeMirror source range');
  click('tab-bytecode');
  assert(!!document.querySelector('.editor-trace-range'), 'switching tabs keeps the selected source highlight');
  [...el('bytecode-instructions').querySelectorAll('[data-instruction-id]')].find(row => row.textContent.includes('BINARY_OP') && row.textContent.includes('3:')).click();
  assert(editor.getSelection() === 'x + y' && el('bytecode-instructions').querySelector('.is-selected')?.textContent.includes('BINARY_OP'), 'bytecode instruction jumps to CPython source location');
  click('tab-disassembly');
  [...el('disassembly-instructions').querySelectorAll('[data-instruction-id]')].find(row => row.textContent.includes('LOAD_NAME') && row.textContent.includes('3:')).click();
  assert(editor.getSelection() === 'x' && el('disassembly-instructions').querySelector('.is-selected')?.textContent.includes('LOAD_NAME'), 'disassembly instruction maps back to a specific source name');
  click('tab-trace'); click('clear-trace');
  assert(!document.querySelector('.editor-trace-range') && !document.querySelector('.editor-trace-line') && !editor.getSelection() && el('clear-trace').hidden, 'clearing selection removes CodeMirror marks and related state');
  editor.setCursor({ line: 0, ch: 0 }); editor.replaceRange('q', { line: 0, ch: 0 }, { line: 0, ch: 1 });
  assert(el('trace-content').textContent.includes('Run again') && !document.querySelector('.editor-trace-line'), 'source edits invalidate cached selections');
  editor.setValue('def hello('); click('run-button');
  await until(() => el('runtime-status').textContent === 'PYTHON READY' && el('errors-content').textContent.includes('SyntaxError'), 'invalid trace execution', 20000);
  editor.setCursor({ line: 0, ch: 1 });
  assert(el('trace-content').textContent.includes('def') && el('trace-content').textContent.includes('Unavailable'), 'invalid source traces partial tokens and explicitly unavailable later stages');
  editor.setValue('def add(a, b):\n    return a + b\nresult = add(2, 3)\nprint(result)'); click('run-button');
  await until(() => el('runtime-status').textContent === 'PYTHON READY' && el('output-content').textContent === '5\n', 'nested function trace', 20000);
  click('tab-bytecode');
  const functionRow = [...el('bytecode-instructions').querySelectorAll('[data-instruction-id^="co-1:"]')].find(row => row.textContent.includes('BINARY_OP'));
  assert(!!functionRow && el('bytecode-instructions').textContent.includes('CODE OBJECT  <module>') && el('bytecode-instructions').textContent.includes('CODE OBJECT  add'), 'module and function instructions remain distinct');
  functionRow.click();
  assert(editor.getSelection() === 'a + b', 'nested function bytecode maps to its own source');
  editor.setValue('for i in range(5):\n    if i % 2 == 0:\n        print(i)'); click('run-button');
  await until(() => el('runtime-status').textContent === 'PYTHON READY' && el('output-content').textContent === '0\n2\n4\n', 'loop trace', 20000);
  editor.setCursor({ line: 1, ch: 7 });
  assert(el('trace-content').textContent.includes('COMPARE_OP') && el('trace-content').textContent.includes('BINARY_OP'), 'condition line relates to multiple instructions');
  editor.setValue('café = "🙂"\nprint(café)'); click('run-button');
  await until(() => el('runtime-status').textContent === 'PYTHON READY' && el('output-content').textContent === '🙂\n', 'Unicode trace', 20000);
  click('tab-ast');
  [...el('ast-node-list').querySelectorAll('[data-ast-id]')].find(row => row.textContent.startsWith("Constant (value='🙂')")).click();
  assert(editor.getSelection() === '"🙂"', 'UTF-8 CPython columns highlight the correct UTF-16 editor range');
  return { passed: checks.length, checks };
}
